SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE SCHEMA `angwebapp` ;

CREATE TABLE IF NOT EXISTS `USERS` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `MIDDLE_NAME` VARCHAR(100) ,
  `LAST_NAME` VARCHAR(100),
  `EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `USER_PROFILE` (
  `USER_NAME` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `ACCESS_LIST` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USER_NAME`)
);


COMMIT;